# Generated by Django 4.2.3 on 2023-09-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='foto',
            field=models.ImageField(default=1, upload_to='info-harga/foto'),
            preserve_default=False,
        ),
    ]
